# ---- Base Node ----
FROM node:24-alpine AS base
WORKDIR /app
COPY services/streaming-proxy/package*.json ./
RUN npm ci

# ---- Production ----
FROM node:24-alpine AS production
WORKDIR /app
COPY --from=base /app/node_modules ./node_modules
COPY services/streaming-proxy/ ./
EXPOSE 3001
CMD [ "npm", "start" ]
