# Build configuration to exclude web platform for non-web builds
targets:
  $default:
    builders:
      # Exclude web-specific code from non-web builds
      flutter_tools|build_runner:
        options:
          platforms:
            - windows
            - linux
            - android
