apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-backend
  namespace: argocd
operation:
  sync:
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true