// Mocks generated by Mockito 5.4.6 from annotations
// in cloudtolocalllm/test/performance/setup_wizard_performance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i10;

import 'package:cloudtolocalllm/models/container_creation_result.dart' as _i7;
import 'package:cloudtolocalllm/models/download_option.dart' as _i15;
import 'package:cloudtolocalllm/models/platform_config.dart' as _i14;
import 'package:cloudtolocalllm/models/setup_error.dart' as _i12;
import 'package:cloudtolocalllm/services/auth_service.dart' as _i8;
import 'package:cloudtolocalllm/services/download_management_service.dart'
    as _i17;
import 'package:cloudtolocalllm/services/platform_detection_service.dart'
    as _i13;
import 'package:cloudtolocalllm/services/setup_error_analytics_service.dart'
    as _i5;
import 'package:cloudtolocalllm/services/setup_error_recovery_service.dart'
    as _i3;
import 'package:cloudtolocalllm/services/setup_troubleshooting_service.dart'
    as _i4;
import 'package:cloudtolocalllm/services/setup_wizard_service.dart' as _i11;
import 'package:cloudtolocalllm/services/user_container_service.dart' as _i16;
import 'package:flutter/foundation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetupErrorRecoveryService_1 extends _i1.SmartFake
    implements _i3.SetupErrorRecoveryService {
  _FakeSetupErrorRecoveryService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetupTroubleshootingService_2 extends _i1.SmartFake
    implements _i4.SetupTroubleshootingService {
  _FakeSetupTroubleshootingService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetupErrorAnalyticsService_3 extends _i1.SmartFake
    implements _i5.SetupErrorAnalyticsService {
  _FakeSetupErrorAnalyticsService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetupErrorRecoveryResult_4 extends _i1.SmartFake
    implements _i3.SetupErrorRecoveryResult {
  _FakeSetupErrorRecoveryResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_5<T1> extends _i1.SmartFake implements _i6.Future<T1> {
  _FakeFuture_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTroubleshootingSession_6 extends _i1.SmartFake
    implements _i4.TroubleshootingSession {
  _FakeTroubleshootingSession_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSetupAnalyticsSummary_7 extends _i1.SmartFake
    implements _i5.SetupAnalyticsSummary {
  _FakeSetupAnalyticsSummary_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContainerCreationResult_8 extends _i1.SmartFake
    implements _i7.ContainerCreationResult {
  _FakeContainerCreationResult_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<bool> get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#isAuthenticated),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  _i2.ValueNotifier<bool> get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeValueNotifier_0<bool>(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i2.ValueNotifier<bool>);

  @override
  bool get isWeb =>
      (super.noSuchMethod(Invocation.getter(#isWeb), returnValue: false)
          as bool);

  @override
  bool get isMobile =>
      (super.noSuchMethod(Invocation.getter(#isMobile), returnValue: false)
          as bool);

  @override
  bool get isDesktop =>
      (super.noSuchMethod(Invocation.getter(#isDesktop), returnValue: false)
          as bool);

  @override
  bool get isValidatingToken =>
      (super.noSuchMethod(
            Invocation.getter(#isValidatingToken),
            returnValue: false,
          )
          as bool);

  @override
  bool get supportsBiometrics =>
      (super.noSuchMethod(
            Invocation.getter(#supportsBiometrics),
            returnValue: false,
          )
          as bool);

  @override
  bool get supportsDeepLinking =>
      (super.noSuchMethod(
            Invocation.getter(#supportsDeepLinking),
            returnValue: false,
          )
          as bool);

  @override
  bool get supportsSecureStorage =>
      (super.noSuchMethod(
            Invocation.getter(#supportsSecureStorage),
            returnValue: false,
          )
          as bool);

  @override
  String get recommendedAuthMethod =>
      (super.noSuchMethod(
            Invocation.getter(#recommendedAuthMethod),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#recommendedAuthMethod),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> login() =>
      (super.noSuchMethod(
            Invocation.method(#login, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> handleCallback() =>
      (super.noSuchMethod(
            Invocation.method(#handleCallback, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> loginWithBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithBiometrics, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> refreshTokenIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokenIfNeeded, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, dynamic> getPlatformInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getPlatformInfo, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<String?> getValidatedAccessToken({bool? forceRefresh = false}) =>
      (super.noSuchMethod(
            Invocation.method(#getValidatedAccessToken, [], {
              #forceRefresh: forceRefresh,
            }),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<void> loginWithPersistence() =>
      (super.noSuchMethod(
            Invocation.method(#loginWithPersistence, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logoutWithCleanup() =>
      (super.noSuchMethod(
            Invocation.method(#logoutWithCleanup, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> validateAuthentication() =>
      (super.noSuchMethod(
            Invocation.method(#validateAuthentication, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SetupWizardService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetupWizardService extends _i1.Mock
    implements _i11.SetupWizardService {
  MockSetupWizardService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSetupCompleted =>
      (super.noSuchMethod(
            Invocation.getter(#isSetupCompleted),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasUserSeenWizard =>
      (super.noSuchMethod(
            Invocation.getter(#hasUserSeenWizard),
            returnValue: false,
          )
          as bool);

  @override
  bool get shouldShowWizard =>
      (super.noSuchMethod(
            Invocation.getter(#shouldShowWizard),
            returnValue: false,
          )
          as bool);

  @override
  bool get isFirstTimeUser =>
      (super.noSuchMethod(
            Invocation.getter(#isFirstTimeUser),
            returnValue: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get canAccessFromSettings =>
      (super.noSuchMethod(
            Invocation.getter(#canAccessFromSettings),
            returnValue: false,
          )
          as bool);

  @override
  _i3.SetupErrorRecoveryService get errorRecoveryService =>
      (super.noSuchMethod(
            Invocation.getter(#errorRecoveryService),
            returnValue: _FakeSetupErrorRecoveryService_1(
              this,
              Invocation.getter(#errorRecoveryService),
            ),
          )
          as _i3.SetupErrorRecoveryService);

  @override
  _i4.SetupTroubleshootingService get troubleshootingService =>
      (super.noSuchMethod(
            Invocation.getter(#troubleshootingService),
            returnValue: _FakeSetupTroubleshootingService_2(
              this,
              Invocation.getter(#troubleshootingService),
            ),
          )
          as _i4.SetupTroubleshootingService);

  @override
  _i5.SetupErrorAnalyticsService get analyticsService =>
      (super.noSuchMethod(
            Invocation.getter(#analyticsService),
            returnValue: _FakeSetupErrorAnalyticsService_3(
              this,
              Invocation.getter(#analyticsService),
            ),
          )
          as _i5.SetupErrorAnalyticsService);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> markWizardSeen() =>
      (super.noSuchMethod(
            Invocation.method(#markWizardSeen, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> markSetupCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#markSetupCompleted, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> resetSetupState() =>
      (super.noSuchMethod(
            Invocation.method(#resetSetupState, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void showWizard() => super.noSuchMethod(
    Invocation.method(#showWizard, []),
    returnValueForMissingStub: null,
  );

  @override
  void hideWizard() => super.noSuchMethod(
    Invocation.method(#hideWizard, []),
    returnValueForMissingStub: null,
  );

  @override
  void showWizardFromSettings() => super.noSuchMethod(
    Invocation.method(#showWizardFromSettings, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getSetupProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getSetupProgress, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<_i3.SetupErrorRecoveryResult> handleSetupError(
    dynamic exception, {
    String? setupStep,
    Map<String, dynamic>? context = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #handleSetupError,
              [exception],
              {#setupStep: setupStep, #context: context},
            ),
            returnValue: _i6.Future<_i3.SetupErrorRecoveryResult>.value(
              _FakeSetupErrorRecoveryResult_4(
                this,
                Invocation.method(
                  #handleSetupError,
                  [exception],
                  {#setupStep: setupStep, #context: context},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.SetupErrorRecoveryResult>);

  @override
  _i6.Future<T> executeSetupOperation<T>(
    String? operationName,
    _i6.Future<T> Function()? operation, {
    int? maxRetries = 3,
    String? setupStep,
    Map<String, dynamic>? context = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #executeSetupOperation,
              [operationName, operation],
              {
                #maxRetries: maxRetries,
                #setupStep: setupStep,
                #context: context,
              },
            ),
            returnValue:
                _i9.ifNotNull(
                  _i9.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #executeSetupOperation,
                      [operationName, operation],
                      {
                        #maxRetries: maxRetries,
                        #setupStep: setupStep,
                        #context: context,
                      },
                    ),
                  ),
                  (T v) => _i6.Future<T>.value(v),
                ) ??
                _FakeFuture_5<T>(
                  this,
                  Invocation.method(
                    #executeSetupOperation,
                    [operationName, operation],
                    {
                      #maxRetries: maxRetries,
                      #setupStep: setupStep,
                      #context: context,
                    },
                  ),
                ),
          )
          as _i6.Future<T>);

  @override
  _i4.TroubleshootingSession startTroubleshooting(
    _i12.SetupError? error, {
    Map<String, dynamic>? context = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #startTroubleshooting,
              [error],
              {#context: context},
            ),
            returnValue: _FakeTroubleshootingSession_6(
              this,
              Invocation.method(
                #startTroubleshooting,
                [error],
                {#context: context},
              ),
            ),
          )
          as _i4.TroubleshootingSession);

  @override
  List<_i4.TroubleshootingGuide> getContextualHelp(
    String? setupStep, {
    String? platform,
    Map<String, dynamic>? context = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getContextualHelp,
              [setupStep],
              {#platform: platform, #context: context},
            ),
            returnValue: <_i4.TroubleshootingGuide>[],
          )
          as List<_i4.TroubleshootingGuide>);

  @override
  _i6.Future<void> submitTroubleshootingFeedback(
    _i4.TroubleshootingFeedback? feedback,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#submitTroubleshootingFeedback, [feedback]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> completeSetupSession({
    bool? success = false,
    String? finalStep,
    Map<String, dynamic>? context = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(#completeSetupSession, [], {
              #success: success,
              #finalStep: finalStep,
              #context: context,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i5.SetupAnalyticsSummary getSetupAnalytics({
    DateTime? since,
    String? platform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSetupAnalytics, [], {
              #since: since,
              #platform: platform,
            }),
            returnValue: _FakeSetupAnalyticsSummary_7(
              this,
              Invocation.method(#getSetupAnalytics, [], {
                #since: since,
                #platform: platform,
              }),
            ),
          )
          as _i5.SetupAnalyticsSummary);

  @override
  void resetErrorRecovery() => super.noSuchMethod(
    Invocation.method(#resetErrorRecovery, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [PlatformDetectionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlatformDetectionService extends _i1.Mock
    implements _i13.PlatformDetectionService {
  MockPlatformDetectionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i14.PlatformType get currentPlatform =>
      (super.noSuchMethod(
            Invocation.getter(#currentPlatform),
            returnValue: _i14.PlatformType.windows,
          )
          as _i14.PlatformType);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i14.PlatformType detectPlatform() =>
      (super.noSuchMethod(
            Invocation.method(#detectPlatform, []),
            returnValue: _i14.PlatformType.windows,
          )
          as _i14.PlatformType);

  @override
  void selectPlatform(_i14.PlatformType? platform) => super.noSuchMethod(
    Invocation.method(#selectPlatform, [platform]),
    returnValueForMissingStub: null,
  );

  @override
  void clearPlatformSelection() => super.noSuchMethod(
    Invocation.method(#clearPlatformSelection, []),
    returnValueForMissingStub: null,
  );

  @override
  List<_i15.DownloadOption> getDownloadOptions([_i14.PlatformType? platform]) =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadOptions, [platform]),
            returnValue: <_i15.DownloadOption>[],
          )
          as List<_i15.DownloadOption>);

  @override
  String getInstallationInstructions(
    _i14.PlatformType? platform,
    String? downloadType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getInstallationInstructions, [
              platform,
              downloadType,
            ]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getInstallationInstructions, [
                platform,
                downloadType,
              ]),
            ),
          )
          as String);

  @override
  List<_i14.PlatformType> getSupportedPlatforms() =>
      (super.noSuchMethod(
            Invocation.method(#getSupportedPlatforms, []),
            returnValue: <_i14.PlatformType>[],
          )
          as List<_i14.PlatformType>);

  @override
  bool isPlatformSupported(_i14.PlatformType? platform) =>
      (super.noSuchMethod(
            Invocation.method(#isPlatformSupported, [platform]),
            returnValue: false,
          )
          as bool);

  @override
  void refreshDetection() => super.noSuchMethod(
    Invocation.method(#refreshDetection, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getDetectionInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getDetectionInfo, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserContainerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserContainerService extends _i1.Mock
    implements _i16.UserContainerService {
  MockUserContainerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isCreatingContainer =>
      (super.noSuchMethod(
            Invocation.getter(#isCreatingContainer),
            returnValue: false,
          )
          as bool);

  @override
  bool get isCheckingStatus =>
      (super.noSuchMethod(
            Invocation.getter(#isCheckingStatus),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasActiveContainer =>
      (super.noSuchMethod(
            Invocation.getter(#hasActiveContainer),
            returnValue: false,
          )
          as bool);

  @override
  bool get isContainerCreationSupported =>
      (super.noSuchMethod(
            Invocation.getter(#isContainerCreationSupported),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<_i7.ContainerCreationResult> createUserContainer({
    bool? testMode = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createUserContainer, [], {#testMode: testMode}),
            returnValue: _i6.Future<_i7.ContainerCreationResult>.value(
              _FakeContainerCreationResult_8(
                this,
                Invocation.method(#createUserContainer, [], {
                  #testMode: testMode,
                }),
              ),
            ),
          )
          as _i6.Future<_i7.ContainerCreationResult>);

  @override
  _i6.Future<Map<String, dynamic>> checkContainerStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkContainerStatus, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  _i6.Future<bool> validateContainerHealth() =>
      (super.noSuchMethod(
            Invocation.method(#validateContainerHealth, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> stopUserContainer() =>
      (super.noSuchMethod(
            Invocation.method(#stopUserContainer, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>> getContainerInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getContainerInfo, []),
            returnValue: _i6.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i6.Future<Map<String, dynamic>>);

  @override
  void resetContainerState() => super.noSuchMethod(
    Invocation.method(#resetContainerState, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [DownloadManagementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDownloadManagementService extends _i1.Mock
    implements _i17.DownloadManagementService {
  MockDownloadManagementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isCacheValid =>
      (super.noSuchMethod(Invocation.getter(#isCacheValid), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<String> generateDownloadUrl(
    String? platform,
    String? packageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#generateDownloadUrl, [platform, packageType]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#generateDownloadUrl, [
                  platform,
                  packageType,
                ]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<bool> validateDownload(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#validateDownload, [filePath]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<String>> getAlternativeDownloadUrls(String? platform) =>
      (super.noSuchMethod(
            Invocation.method(#getAlternativeDownloadUrls, [platform]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> trackDownloadEvent(
    String? userId,
    String? platform,
    String? packageType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#trackDownloadEvent, [
              userId,
              platform,
              packageType,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, dynamic> getDownloadStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  void clearTrackingData() => super.noSuchMethod(
    Invocation.method(#clearTrackingData, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> refreshCache() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCache, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i10.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
