name: Build and Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
        description: "The version to build (e.g. 7.11.0+...)"
      docker_version:
        required: true
        type: string
        description: "Docker-safe version tag"
      do_managed:
        required: false
        type: boolean
        default: false
      do_local:
        required: false
        type: boolean
        default: false
      do_desktop:
        required: false
        type: boolean
        default: false
      do_mobile:
        required: false
        type: boolean
        default: false
      reasoning:
        required: false
        type: string
        default: "Manual Trigger"

permissions:
  contents: write
  id-token: write

env:
  AZURE_RESOURCE_GROUP: cloudtolocalllm-rg
  AZURE_CLUSTER_NAME: cloudtolocalllm-aks
  ACR_NAME: imrightguycloudtolocalllm

jobs:
  # ==================================================================================
  # CLOUD INFRASTRUCTURE
  # ==================================================================================
  setup_acr:
    if: inputs.do_managed || inputs.do_local
    runs-on: ubuntu-latest
    outputs:
      login_server: ${{ steps.acr_setup.outputs.login_server }}
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setup ACR
        id: acr_setup
        run: |
          az acr create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.ACR_NAME }} --sku Basic --admin-enabled true --query "provisioningState" --output tsv
          LOGIN_SERVER=$(az acr show --name ${{ env.ACR_NAME }} --query loginServer --output tsv)
          echo "login_server=$LOGIN_SERVER" >> $GITHUB_OUTPUT

  # Parallel Build Jobs
  build_containers:
    needs: setup_acr
    if: inputs.do_managed || inputs.do_local
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [base, postgres, web, api-backend, streaming-proxy]
    steps:
      - uses: actions/checkout@v6

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker Login
        run: |
          ACR_USERNAME=$(az acr credential show --name ${{ env.ACR_NAME }} --query username --output tsv)
          ACR_PASSWORD=$(az acr credential show --name ${{ env.ACR_NAME }} --query passwords[0].value --output tsv)
          echo "$ACR_PASSWORD" | docker login "${{ needs.setup_acr.outputs.login_server }}" --username "$ACR_USERNAME" --password-stdin

      - name: Setup Flutter
        if: matrix.service == 'web'
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Update Versions
        run: |
          chmod +x scripts/update-all-versions.sh
          ./scripts/update-all-versions.sh "${{ inputs.version }}" "${{ github.sha }}"

      - name: Build Flutter Web
        if: matrix.service == 'web'
        run: |
          flutter pub get
          flutter build web --release --no-tree-shake-icons

      - uses: docker/setup-buildx-action@v3

      - name: Build and Push ${{ matrix.service }}
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service == 'api-backend' && 'services/api-backend' || matrix.service == 'streaming-proxy' && 'services/streaming-proxy' || '.' }}
          file: ${{ matrix.service == 'base' && 'config/docker/Dockerfile.base' || matrix.service == 'postgres' && 'config/docker/Dockerfile.postgres' || matrix.service == 'web' && 'web/Dockerfile' || matrix.service == 'api-backend' && 'services/api-backend/Dockerfile' || 'services/streaming-proxy/Dockerfile' }}
          push: true
          tags: |
            ${{ needs.setup_acr.outputs.login_server }}/${{ matrix.service }}:${{ inputs.docker_version }}${{ matrix.service != 'web' && matrix.service != 'base' && '-' || '' }}${{ matrix.service != 'web' && matrix.service != 'base' && matrix.service || '' }}
            ${{ needs.setup_acr.outputs.login_server }}/${{ matrix.service }}:latest
          build-args: |
            BASE_REGISTRY=${{ needs.setup_acr.outputs.login_server }}
          cache-from: type=registry,ref=${{ needs.setup_acr.outputs.login_server }}/${{ matrix.service }}:latest
          cache-to: type=inline

  # Update Kubernetes Manifests (GitOps)
  update_manifests:
    needs: [setup_acr, build_containers]
    if: inputs.do_managed || inputs.do_local
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT_TOKEN || secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update Image Tags
        run: |
          # Install kustomize if needed or use sed
          # Here using sed to update image tags in base deployments
          REGISTRY="${{ needs.setup_acr.outputs.login_server }}"
          VERSION="${{ inputs.docker_version }}"

          # Update web
          sed -i "s|image: .*/web:.*|image: $REGISTRY/web:$VERSION|g" k8s/base/deployments/web.yaml

          # Update api-backend
          sed -i "s|image: .*/api-backend:.*|image: $REGISTRY/api-backend:$VERSION-api-backend|g" k8s/base/deployments/api-backend.yaml

          # Update streaming-proxy (if it has a deployment)
          # sed -i "s|image: .*/streaming-proxy:.*|image: $REGISTRY/streaming-proxy:$VERSION|g" k8s/base/deployments/streaming-proxy.yaml || true

      - name: Commit and Push
        run: |
          git add k8s/base/deployments/*.yaml
          if ! git diff --cached --quiet; then
            git commit -m "deploy(k8s): update images to ${{ inputs.docker_version }} [skip ci]"
            git pull --rebase origin main
            git push origin main
          fi

  # ==================================================================================
  # DESKTOP BUILD
  # ==================================================================================
  desktop_build:
    if: inputs.do_desktop
    runs-on: windows-2022
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Update Versions
        shell: bash
        run: |
          chmod +x scripts/update-all-versions.sh
          ./scripts/update-all-versions.sh "${{ inputs.version }}" "${{ github.sha }}"

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Windows
        run: |
          flutter build windows --release --verbose --dart-define=FLUTTER_BUILD_NUMBER=${{ github.sha }}

      - name: Create Installer
        shell: powershell
        run: |
          # Use existing script
          ./scripts/powershell/Build-GitHubReleaseAssets.ps1 -SkipBuild -InstallInnoSetup -Version "${{ inputs.version }}"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-desktop-${{ inputs.version }}
          path: dist/windows/*

  # ==================================================================================
  # RELEASE
  # ==================================================================================
  create_release:
    needs: [update_manifests, desktop_build]
    if: always() && (needs.update_manifests.result == 'success' || needs.desktop_build.result == 'success' || inputs.do_mobile)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Download Windows Artifacts
        if: needs.desktop_build.result == 'success'
        uses: actions/download-artifact@v4
        with:
          name: windows-desktop-${{ inputs.version }}
          path: release-assets/

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ inputs.version }}" \
            --title "CloudToLocalLLM v${{ inputs.version }}" \
            --notes "Automated release based on: ${{ inputs.reasoning }}" \
            --target main \
            $(find release-assets -maxdepth 1 -type f)
